// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Truck_Registration_Control.Data;

namespace Truck_Registration_Control.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210107230322_initialCreate")]
    partial class initialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Truck_Registration_Control.Domain.Truck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<int>("TruckModelId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("YearManufacturing")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("YearModel")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TruckModelId");

                    b.ToTable("Truck");
                });

            modelBuilder.Entity("Truck_Registration_Control.Domain.TruckModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TruckModel");
                });

            modelBuilder.Entity("Truck_Registration_Control.Domain.Truck", b =>
                {
                    b.HasOne("Truck_Registration_Control.Domain.TruckModel", "TruckModel")
                        .WithMany()
                        .HasForeignKey("TruckModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TruckModel");
                });
#pragma warning restore 612, 618
        }
    }
}
